<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'annotations.reader' shared service.

include_once \dirname(__DIR__, 4).'/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/Reader.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php';

$this->privates['annotations.reader'] = $instance = new \Doctrine\Common\Annotations\AnnotationReader();

$a = new \Doctrine\Common\Annotations\AnnotationRegistry();
$a->registerUniqueLoader('class_exists');

$instance->addGlobalIgnoredName('required', $a);

return $instance;
