<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AppController::read' => ['privates', '.service_locator.otlINqy', 'get_ServiceLocator_OtlINqyService.php', true],
    'App\\Controller\\AppController::update' => ['privates', '.service_locator.otlINqy', 'get_ServiceLocator_OtlINqyService.php', true],
    'App\\Controller\\AppController:read' => ['privates', '.service_locator.otlINqy', 'get_ServiceLocator_OtlINqyService.php', true],
    'App\\Controller\\AppController:update' => ['privates', '.service_locator.otlINqy', 'get_ServiceLocator_OtlINqyService.php', true],
], [
    'App\\Controller\\AppController::read' => '?',
    'App\\Controller\\AppController::update' => '?',
    'App\\Controller\\AppController:read' => '?',
    'App\\Controller\\AppController:update' => '?',
]));
