<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'maker.entity_class_generator' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/maker-bundle/src/Doctrine/EntityClassGenerator.php';

$this->privates['maker.entity_class_generator'] = $instance = new \Symfony\Bundle\MakerBundle\Doctrine\EntityClassGenerator(($this->privates['maker.generator'] ?? $this->load('getMaker_GeneratorService.php')), ($this->privates['maker.doctrine_helper'] ?? $this->load('getMaker_DoctrineHelperService.php')));

$instance->setMangerRegistryClassName('Doctrine\\Persistence\\ManagerRegistry');

return $instance;
