<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEUUOEAk\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEUUOEAk/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEUUOEAk.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEUUOEAk\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEUUOEAk\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EUUOEAk',
    'container.build_id' => 'd41d2caf',
    'container.build_time' => 1682349671,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEUUOEAk');
