<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_app_read' => [[], ['_controller' => 'App\\Controller\\AppController::read'], [], [['text', '/']], [], []],
    'app_app_insert' => [[], ['_controller' => 'App\\Controller\\AppController::insert'], [], [['text', '/insert']], [], []],
    'app_app_update' => [['id'], ['_controller' => 'App\\Controller\\AppController::update'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/update']], [], []],
    'app_app_ping' => [[], ['_controller' => 'App\\Controller\\AppController::ping'], [], [['text', '/ping']], [], []],
];
